### ISSUE TITLE
Test openshift ci configuration

### ISSUE THREAD

**Issue by dipak-pawar** [codeready-toolchain/host-operator#4]
As you are enabling shrug plugin https://github.com/openshift/release/pull/4025/files#diff-5da33c7edc88b9ba312e0e1eda240a8fR720, after merging the pr, `/shrug` should be able to add label to issue.

Please close it, when you are done with testing openshift ci

**Comment by xcoulon** [comment]
🤷‍♂️?

**Comment by dipak-pawar** [comment]
closing issue as `openshift-ci` configured and working fine.
