### ISSUE TITLE
Delete DbaaSTenant code from user template

### ISSUE THREAD

**Issue by fOO223Fr** [codeready-toolchain/host-operator#672]
RHODA has moved away from the use of dbaastenant object. Therefore for new sandbox user signup would not need this piece of code to be ran https://github.com/codeready-toolchain/host-operator/commit/127897eff1ff1a3a2937e040d67d3caaaef6d752 .

**Comment by jeremyary** [comment]
https://github.com/codeready-toolchain/host-operator/pull/673

**Comment by alexeykazakov** [comment]
https://github.com/codeready-toolchain/host-operator/pull/674
